### ISSUE TITLE
YouTube Filtering

### ISSUE THREAD

**Issue by TorpedoBE** [fifthsegment/GateSentry#1]
Hi,

I would like to use GatSentry to filter my daughters youtube movies.

Problem is that if I download the certificate an error is thrown. (This file cann't be used for securty certificate).

Can you pleas explain to me how to implement youtube filtering?

Bart

**Comment by fifthsegment** [comment]
Hi Bart,

Youtube+ filtering on Youtube is working for me with on GateSentry's default settings with GateSentry's certificate. Here's a screenshot from a PC on my network (on the top left you'll see it's loaded Youtube on GateSentry's certificate codenamed AI ):

![http://i.imgur.com/Wws4xEO.png](http://i.imgur.com/Wws4xEO.png)



Here's GateSentry blocking a search term, zoom in to see the url:


![http://i.imgur.com/CYGpQy5.png](http://i.imgur.com/CYGpQy5.png)


I'm not sure what's causing the problem on your system. However, here are a few things to try:



* Are you sure you're using the right certificate? . This version came with a different certificate, so you will have to change the certificate on any devices using the old certificate. Make sure you're using this certificate AI.p7b: 

https://www.dropbox.com/s/5ozinfwh71w8b3z/AI.p7b?dl=0



* **Optional, but worth a try** Make sure you check all the trust settings when you import the certificate
![http://i.imgur.com/4hQucZg.png](http://i.imgur.com/4hQucZg.png)



* Some times if you've used the wrong certificate or incorrect settings, the browser will cache those, after that no matter how many times you make further changes to settings the same error would show up. In such a case try fresh in a new browser like [Firefox portable edition](http://portableapps.com/apps/internet/firefox_portable), download the correct certificate, import it making sure you're using correct settings, set proxy then browse to Youtube.

**Comment by TorpedoBE** [comment]
hi Abdullah,

In my case firefox tells me that youtube is verified by Google inc. and not AI.

I installed the certifacte of your dropbox in firefox portable but still no luck.

Bart

**Comment by fifthsegment** [comment]
Okay, have you enabled https proxy in Firefox?
![ssl-proxy](https://cloud.githubusercontent.com/assets/5513549/15797423/20a18bc4-2a31-11e6-97cb-530f5745b205.PNG)

**Comment by TorpedoBE** [comment]
that seems to be the problem....

Thanks for you support
