### ISSUE TITLE
Internet not working over hotspot (using LAN)

### ISSUE THREAD

**Issue by ketutjoko13** [fifthsegment/Gatesentry#11]
Hi Abdullah,

I'm using **backupSmall.img** RPi2 with wifi dongle plugged. It's working well for Hotspot and blocking site or phrase without internet. But when I will try to share the internet over LAN cabel plugged in RPi2, the internet not shared over wifi. 

Also I try to install the certificate. But it doesn't work.

Please help,
Thank You
Ketut

**Comment by fifthsegment** [comment]
Hi Ketut,

I personally only tested this image with a Raspberry Pi 3 which already has an existing wifi module hence it supports hotspot mode out of the box. If you use a Raspberry Pi 2, the only way I recommend to use GateSentry is not using a dongle, rather use it via your LAN,  like this:  

![Use GateSentry via Lan](http://www.abdullahirfan.com/wp-content/uploads/2015/03/rpi-setup-750x859.jpg)

**Regarding the certificate:**

How are you trying to install it ? What browser are you using?


Thanks!


Abdullah

**Comment by ketutjoko13** [comment]
Hi Abdullah,

Thanks for reply... respect from indonesia!

I hope can make internet filter over wifi AP with GateSentry.
What Im doing  : 

1. Install GateSentry (the backupSmall.img) 
2. Plug Dongle and LAN then turn on raspberry pi 2
3. I connecting my laptop over wifi to the GateSentry-AP, login Web Configuration is ok and ssh login is ok.
4.  I install certificate to my laptop from this link : https://mega.nz/#!cEkmGRQD!kEPK0YfRDmDWaIo1Q3VcBXtceln43q-9IgTTNTaAe28
and hope internet will work, but it doesn't work. The problem there is no internet access from Rpi, I try from ssh to "ping google.com" not working and try _sudo apt-get install raspi-config_ but I'm not lucky... :(

The LAN have good conection internet when I connecting it to my laptop directly.

Let me know what do you think..


Thank You

Joko
