### ISSUE TITLE
Is it possible to use Gate Sentry as a transparent proxy?

### ISSUE THREAD

**Issue by leeand00** [fifthsegment/GateSentry#2]
If I set all of my firewall rules correctly, is it possible to use Gate Sentry as a transparent proxy?

**Comment by fifthsegment** [comment]
With the current configuration of Squid; It is possible for http but not for https. I tried it once http worked fine, but I only got certificate errors with https.

My solution was using GateSentry's own built-in Wifi AP to connect clients with it. Works by default on Pi3, and Pi2 (if you have a working Wifi adapter). If you use GateSentry's own AP you don't need to configure any proxy settings on the clients, filtering just works (just like transparent proxying). All you'd need to do is install GateSentry's certificate on client systems.

**Comment by leeand00** [comment]
Okay thanks!
