### ISSUE TITLE
GateSentry is blocking all traffic

### ISSUE THREAD

**Issue by vince2bir** [fifthsegment/Gatesentry#3]
I wanted to modify the squid.conf file (to add tmpfs cache). This did not work out too well, everything being blocked thereafter. Then I reverted to the previous configuration file and restarted but GateSentry keeps blocking all traffic. (I've put the original config file [https://gist.github.com/fifthsegment/79fb356bf4cbf90253104388d504ee43](url) )

**/var/log/squid3/access.log** gives me little information on what is happening : 

```
1464957874.619    407 127.0.0.1 TCP_MISS/500 133277 GET https://www.google.fr/ - PINNED/2a00:1450:4007:80d::2003 text/html
1464957884.167   5768 127.0.0.1 TCP_MISS/500 133282 GET http://google.com/ - HIER_DIRECT/2a00:1450:4007:807::200e text/html
```

**Comment by fifthsegment** [comment]
Okay, seems like a broken pipe issue. After any change that you make to any config file, whether its squid, dansguardian or gatesentry, you **must** restart all three of them to allow the changes to take effect. Otherwise you'll keep getting the everything blocked error.


`service squid3 restart
service dansguardian restart
service gatesentry restart`

**Comment by vince2bir** [comment]
I did it. Same result.
Any ways to get more info in the logs ?
```
1465024727.899   5214 127.0.0.1 TCP_MISS/500 133282 GET http://google.fr/ - HIER_DIRECT/2a00:1450:4007:80c::2003 text/html
1465024738.131   5181 127.0.0.1 TCP_MISS/500 133282 GET http://google.com/ - HIER_DIRECT/2a00:1450:4007:80c::200e text/html
1465024775.533   5525 127.0.0.1 TCP_MISS/500 133282 GET http://yahoo.com/ - HIER_DIRECT/2001:4998:c:a06::2:4008 text/html
1465024777.193    293 127.0.0.1 TCP_MISS/500 133282 GET http://yahoo.com/favicon.ico - HIER_DIRECT/2001:4998:c:a06::2:4008 text/html
1465024778.733    293 127.0.0.1 TCP_MISS/500 133282 GET http://yahoo.com/favicon.ico - HIER_DIRECT/2001:4998:c:a06::2:4008 text/html
```

**Comment by fifthsegment** [comment]
Hmmm...weird. Can you list any changes that you made to the default GS image (any config files/software installed)?

**Comment by vince2bir** [comment]
I created a cache directory
then modified the /etc/fstab
`tmpfs /cache tmpfs defaults,noatime,nosuid,size=500m 0 0
`
the /etc/squid3/squid.conf to activate the cache (commenting other statements)
`cache_dir ufs /cache 400 16 256`
and then
```
service squid3 stop
squid3 -z
service squid3 start
```
I have reverted and removing everything back to original (I think), restarted, rebooting, etc...
