### ISSUE TITLE
Block traffic on tablet

### ISSUE THREAD

**Issue by TorpedoBE** [fifthsegment/Gatesentry#4]
Hi,

Is it possible to use GateSentry for blocking youtube (app) trafic to IOS and android devices?

Bart

**Comment by fifthsegment** [comment]
I'm not sure if I understand you correctly. Do you want to completely disable Youtube traffic for iOS/android clients? If so, then GateSentry doesn't support that. However, you can use GS to filter Youtube traffic on Android and iOS clients by setting up GateSentry as the system proxy on Android and iPhone.

**Comment by TorpedoBE** [comment]
Hi Abdullah,

I want to restrict the content on my Ipad where the youtube app is used.

I already tried to put the GateSentry as proxy but there was no content availble in the youtube app.

So can GatSentry do this?

Bart

**Comment by leeand00** [comment]
Can't you just add the mac address of the tablet, and prevent it from connecting that way?

**Comment by TorpedoBE** [comment]
Hi,


I want the tablet connect to the proxy and filter the traffic.

So I don't think this is a solution.

Bart

**Comment by fifthsegment** [comment]
Okay, so you tried setting GateSentry as the proxy on your tablet but then there was no content available in the Youtube app. Did you install the GateSentry certificate on your tablet?

**Comment by TorpedoBE** [comment]
It wasn't installed so I did but still movies with blocked Phrases ar started with the app.
