### ISSUE TITLE
Why are no instructions given about how to self-sign a certificate?

### ISSUE THREAD

**Issue by leeand00** [fifthsegment/GateSentry#9]
If i'm going to use this as my proxy, then why aren't there any instructions for how to self-sign a certificate / become your own certificate authority for using GateSentry?  That seems like a security hole in the software.

Anyway here is how to do that:

- http://unix.stackexchange.com/questions/289706/images-and-stylesheets-not-loading-from-squid-due-to-a-bad-certificate - My Question on the topic
- http://wiki.squid-cache.org/Features/DynamicSslCert - DynamicSslCert How to for Squid
- https://jamielinux.com/docs/openssl-certificate-authority/create-the-root-pair.html#prepare-the-configuration-file - How to Become a Certificate Authority for yourself.

**Comment by fifthsegment** [comment]
Thanks for that. Yes, self-signed certificates are encouraged. I'll add generation instructions to the README file. 


Please understand, GS  is currently a one man operation, it's not possible for me to do every single thing right; the reason I shared the source here was to get more contributors to iron out bugs like these. If you're able to resolve any issues, just commit it here as well and I'd merge it into the existing code base.

**Comment by leeand00** [comment]
Okay I didn't realize that.  I'm just saying that it looks shady to alot of people if you don't give them instructions to do so...

**Comment by fifthsegment** [comment]
Sorry, super busy these days. I've added the command: https://github.com/fifthsegment/GateSentry/commit/4f1e7c8dc2effc422df6d0e3ca08810ec278aa44
