### ISSUE TITLE
Can the Certificate Expiry Date be set in settings?

### ISSUE THREAD

**Issue by danielparcesepe** [fifthsegment/Gatesentry#93]
Can the Certificate Expiry Date be set in settings?

Just testing and noticed it is set to expire Certificate Expiry: 2024-12-30.

Kind Regards,

**Comment by fifthsegment** [comment]
No, but you can generate a new certificate and copy its contents into the "MITM Filtering Certificate" field.

Instructions to generate one: https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl
